/* SPDX-License-Identifier: GPL-2.0 */


#ifndef _DT_BINDINGS_CADENCE_SERDES_H
#define _DT_BINDINGS_CADENCE_SERDES_H

#define CDNS_SERDES_NO_SSC		0
#define CDNS_SERDES_EXTERNAL_SSC	1
#define CDNS_SERDES_INTERNAL_SSC	2


#define CDNS_TORRENT_REFCLK_DRIVER      0
#define CDNS_TORRENT_DERIVED_REFCLK	1
#define CDNS_TORRENT_RECEIVED_REFCLK	2


#define CDNS_SIERRA_PLL_CMNLC		0
#define CDNS_SIERRA_PLL_CMNLC1		1
#define CDNS_SIERRA_DERIVED_REFCLK	2

#endif 
