

#ifndef __AMD_ASIC_TYPE_H__
#define __AMD_ASIC_TYPE_H__

enum amd_asic_type {
	CHIP_TAHITI = 0,
	CHIP_PITCAIRN,	
	CHIP_VERDE,	
	CHIP_OLAND,	
	CHIP_HAINAN,	
	CHIP_BONAIRE,	
	CHIP_KAVERI,	
	CHIP_KABINI,	
	CHIP_HAWAII,	
	CHIP_MULLINS,	
	CHIP_TOPAZ,	
	CHIP_TONGA,	
	CHIP_FIJI,	
	CHIP_CARRIZO,	
	CHIP_STONEY,	
	CHIP_POLARIS10,	
	CHIP_POLARIS11,	
	CHIP_POLARIS12,	
	CHIP_VEGAM,	
	CHIP_VEGA10,	
	CHIP_VEGA12,	
	CHIP_VEGA20,	
	CHIP_RAVEN,	
	CHIP_ARCTURUS,	
	CHIP_RENOIR,	
	CHIP_ALDEBARAN, 
	CHIP_NAVI10,	
	CHIP_CYAN_SKILLFISH,	
	CHIP_NAVI14,	
	CHIP_NAVI12,	
	CHIP_SIENNA_CICHLID,	
	CHIP_NAVY_FLOUNDER,	
	CHIP_VANGOGH,	
	CHIP_DIMGREY_CAVEFISH,	
	CHIP_BEIGE_GOBY,	
	CHIP_YELLOW_CARP,	
	CHIP_IP_DISCOVERY,	
	CHIP_LAST,
};

extern const char *amdgpu_asic_name[];

#endif 
