/* SPDX-License-Identifier: GPL-2.0 */
#ifndef __ASM_VDSOCLOCKSOURCE_H
#define __ASM_VDSOCLOCKSOURCE_H

#define VDSO_ARCH_CLOCKMODES					\
		\
	VDSO_CLOCKMODE_ARCHTIMER,				\
			\
	VDSO_CLOCKMODE_ARCHTIMER_NOCOMPAT

#endif
