/* SPDX-License-Identifier: (GPL-2.0-only OR BSD-2-Clause) */

#ifndef __DT_TLV320ADC3XXX_H
#define __DT_TLV320ADC3XXX_H

#define ADC3XXX_GPIO_DISABLED		0 
#define ADC3XXX_GPIO_INPUT		1 
#define ADC3XXX_GPIO_GPI		2 
#define ADC3XXX_GPIO_GPO		3 
#define ADC3XXX_GPIO_CLKOUT		4 
#define ADC3XXX_GPIO_INT1		5 
#define ADC3XXX_GPIO_INT2		6 

#define ADC3XXX_GPIO_SECONDARY_BCLK	8 
#define ADC3XXX_GPIO_SECONDARY_WCLK	9 
#define ADC3XXX_GPIO_ADC_MOD_CLK	10 


#define ADC3XXX_MICBIAS_OFF		0 
#define ADC3XXX_MICBIAS_2_0V		1 
#define ADC3XXX_MICBIAS_2_5V		2 
#define ADC3XXX_MICBIAS_AVDD		3 

#endif 
