/* SPDX-License-Identifier: GPL-2.0 */


#ifndef _DT_BINDINGS_REGULATOR_ACT8865_H
#define _DT_BINDINGS_REGULATOR_ACT8865_H



#define ACT8865_REGULATOR_MODE_FIXED		1
#define ACT8865_REGULATOR_MODE_NORMAL		2
#define ACT8865_REGULATOR_MODE_LOWPOWER	3

#endif
