/* SPDX-License-Identifier: GPL-2.0 */

#ifndef _DT_BINDINGS_REGULATOR_MEDIATEK_MT6397_H_
#define _DT_BINDINGS_REGULATOR_MEDIATEK_MT6397_H_



#define MT6397_BUCK_MODE_AUTO		0
#define MT6397_BUCK_MODE_FORCE_PWM	1

#endif
